// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Round_CO2

#include "ui.h"
//#include <Arduino.h>  // Add this line

extern bool useFahrenheit;
extern unsigned long lastSensorRead;
extern const unsigned long sensorInterval;
extern lv_obj_t * ui_TemperatureUnit;

void TemperatureUnits(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        useFahrenheit = lv_obj_has_state(target, LV_STATE_CHECKED);
        
        // Update the temperature unit label immediately
        if (useFahrenheit) {
            lv_label_set_text(ui_TemperatureUnit, "F");
        } else {
            lv_label_set_text(ui_TemperatureUnit, "C");
        }
        
        // Force an immediate sensor read to update the display with new units
        //lastSensorRead = millis() - sensorInterval; // Force immediate read
    }
}

void TemperatureScale(lv_event_t * e)
{
    // Your code here
}