// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Round_CO2

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_CO2Text = NULL;
lv_obj_t * ui_CO2Value = NULL;
lv_obj_t * ui_TemperatureText = NULL;
lv_obj_t * ui_TemperatureValue = NULL;
lv_obj_t * ui_HumidityText = NULL;
lv_obj_t * ui_HumidityValue = NULL;
lv_obj_t * ui_HumidityPPMText = NULL;
lv_obj_t * ui_OnlineText = NULL;
lv_obj_t * ui_NextButton = NULL;
lv_obj_t * ui_SettingsText = NULL;
lv_obj_t * ui_RedLed = NULL;
lv_obj_t * ui_Text400 = NULL;
lv_obj_t * ui_Text2000 = NULL;
lv_obj_t * ui_Label5 = NULL;

lv_obj_t * ui_TemperatureUnit = NULL;  // Add this with other variable declarations

// event funtions
void ui_event_NextButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 200);
    lv_obj_set_height(ui_Arc1, 200);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc1, 15, 35);
    lv_arc_set_value(ui_Arc1, 34);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x072E05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x0DFD5C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_CO2Text = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CO2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2Text, 0);
    lv_obj_set_y(ui_CO2Text, -38);
    lv_obj_set_align(ui_CO2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2Text, "CO2 Level");
    lv_obj_set_style_text_color(ui_CO2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CO2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2Value, -8);
    lv_obj_set_y(ui_CO2Value, -9);
    lv_obj_set_align(ui_CO2Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2Value, "1000");
    lv_obj_set_style_text_color(ui_CO2Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CO2Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CO2Value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CO2Value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TemperatureText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureText, -19);
    lv_obj_set_y(ui_TemperatureText, 27);
    lv_obj_set_align(ui_TemperatureText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureText, "Temperature:");
    lv_obj_set_style_text_color(ui_TemperatureText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TemperatureValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureValue, 43);
    lv_obj_set_y(ui_TemperatureValue, 27);
    lv_obj_set_align(ui_TemperatureValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureValue, "--.-");
    lv_obj_set_style_text_color(ui_TemperatureValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TemperatureValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureValue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);


      // Add this after ui_TemperatureValue creation in ui_Screen1_screen_init()
      ui_TemperatureUnit = lv_label_create(ui_Screen1);
      lv_obj_set_width(ui_TemperatureUnit, LV_SIZE_CONTENT);
      lv_obj_set_height(ui_TemperatureUnit, LV_SIZE_CONTENT);
      lv_obj_set_x(ui_TemperatureUnit, 60);  // Position it next to the temperature value
      lv_obj_set_y(ui_TemperatureUnit, 27);
      lv_obj_set_align(ui_TemperatureUnit, LV_ALIGN_CENTER);
      lv_label_set_text(ui_TemperatureUnit, "C");  // Default to Celsius
      lv_obj_set_style_text_color(ui_TemperatureUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_text_opa(ui_TemperatureUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_text_font(ui_TemperatureUnit, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_HumidityText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HumidityText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityText, -9);
    lv_obj_set_y(ui_HumidityText, 45);
    lv_obj_set_align(ui_HumidityText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityText, "Humidity:");
    lv_obj_set_style_text_color(ui_HumidityText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HumidityValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityValue, 37);
    lv_obj_set_y(ui_HumidityValue, 46);
    lv_obj_set_align(ui_HumidityValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityValue, "--");
    lv_obj_set_style_text_color(ui_HumidityValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityValue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityPPMText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HumidityPPMText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityPPMText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityPPMText, 39);
    lv_obj_set_y(ui_HumidityPPMText, -7);
    lv_obj_set_align(ui_HumidityPPMText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityPPMText, "ppm");
    lv_obj_set_style_text_color(ui_HumidityPPMText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityPPMText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumidityPPMText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnlineText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_OnlineText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnlineText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnlineText, 0);
    lv_obj_set_y(ui_OnlineText, -74);
    lv_obj_set_align(ui_OnlineText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnlineText, "Online");
    lv_obj_set_style_text_color(ui_OnlineText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OnlineText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OnlineText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_NextButton, 72);
    lv_obj_set_height(ui_NextButton, 24);
    lv_obj_set_x(ui_NextButton, 0);
    lv_obj_set_y(ui_NextButton, 85);
    lv_obj_set_align(ui_NextButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NextButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NextButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NextButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NextButton, lv_color_hex(0x5B5959), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NextButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NextButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NextButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NextButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SettingsText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsText, 0);
    lv_obj_set_y(ui_SettingsText, 85);
    lv_obj_set_align(ui_SettingsText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsText, "Brightness");
    lv_obj_set_style_text_color(ui_SettingsText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RedLed = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_RedLed, 5);
    lv_obj_set_height(ui_RedLed, 5);
    lv_obj_set_x(ui_RedLed, 0);
    lv_obj_set_y(ui_RedLed, -60);
    lv_obj_set_align(ui_RedLed, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RedLed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RedLed, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RedLed, lv_color_hex(0xDE2727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RedLed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RedLed, lv_color_hex(0xDE2727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RedLed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RedLed, lv_color_hex(0xDE2727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RedLed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RedLed, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RedLed, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Text400 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Text400, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Text400, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Text400, -62);
    lv_obj_set_y(ui_Text400, 80);
    lv_obj_set_align(ui_Text400, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Text400, "400");
    lv_obj_set_style_text_color(ui_Text400, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Text400, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Text400, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Text2000 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Text2000, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Text2000, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Text2000, 62);
    lv_obj_set_y(ui_Text2000, 80);
    lv_obj_set_align(ui_Text2000, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Text2000, "2000");
    lv_obj_set_style_text_color(ui_Text2000, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Text2000, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Text2000, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 53);
    lv_obj_set_y(ui_Label5, 46);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "%");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_NextButton, ui_event_NextButton, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
	
	ui_TemperatureUnit = NULL;  // Add this with other NULL assignments
	
    ui_Screen1 = NULL;
    ui_Arc1 = NULL;
    ui_CO2Text = NULL;
    ui_CO2Value = NULL;
    ui_TemperatureText = NULL;
    ui_TemperatureValue = NULL;
    ui_HumidityText = NULL;
    ui_HumidityValue = NULL;
    ui_HumidityPPMText = NULL;
    ui_OnlineText = NULL;
    ui_NextButton = NULL;
    ui_SettingsText = NULL;
    ui_RedLed = NULL;
    ui_Text400 = NULL;
    ui_Text2000 = NULL;
    ui_Label5 = NULL;

}
