// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Round_CO2

#include "ui.h"

extern bool useFahrenheit;

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_BrightnessSlider = NULL;
lv_obj_t * ui_BrighnessText = NULL;
lv_obj_t * ui_BackButton = NULL;
lv_obj_t * ui_BackText = NULL;
lv_obj_t * ui_VersionText = NULL;
lv_obj_t * ui_BrightnessValue = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_TempText = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_BrightnessSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_BrightnessValue, target, "", "");
    }
}

void ui_event_BackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        TemperatureUnits(e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
	
	// Initialize the temperature switch state
    //if (useFahrenheit) {
    //lv_obj_add_state(ui_Switch1, LV_STATE_CHECKED);
    //} else {
    //lv_obj_clear_state(ui_Switch1, LV_STATE_CHECKED);
    //}
	
	
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel1, 240);
    lv_obj_set_height(ui_Panel1, 240);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xB3B2B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel1, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSlider = lv_slider_create(ui_Screen2);
    lv_slider_set_range(ui_BrightnessSlider, 25, 100);
    lv_slider_set_value(ui_BrightnessSlider, 25, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BrightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BrightnessSlider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_BrightnessSlider, 180);
    lv_obj_set_height(ui_BrightnessSlider, 25);
    lv_obj_set_x(ui_BrightnessSlider, 0);
    lv_obj_set_y(ui_BrightnessSlider, -27);
    lv_obj_set_align(ui_BrightnessSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0x89CFF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BrightnessSlider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BrightnessSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BrightnessSlider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0x0096FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BrightnessSlider, lv_color_hex(0x0096FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BrightnessSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BrightnessSlider, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0x0096FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BrightnessSlider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BrightnessSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BrightnessSlider, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BrighnessText = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_BrighnessText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrighnessText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrighnessText, -20);
    lv_obj_set_y(ui_BrighnessText, -60);
    lv_obj_set_align(ui_BrighnessText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrighnessText, "Brightness:");
    lv_obj_set_style_text_color(ui_BrighnessText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrighnessText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrighnessText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BackButton, 72);
    lv_obj_set_height(ui_BackButton, 24);
    lv_obj_set_x(ui_BackButton, 0);
    lv_obj_set_y(ui_BackButton, 85);
    lv_obj_set_align(ui_BackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButton, lv_color_hex(0x5B5959), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackText = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_BackText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BackText, 0);
    lv_obj_set_y(ui_BackText, 85);
    lv_obj_set_align(ui_BackText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackText, "Back");
    lv_obj_set_style_text_color(ui_BackText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionText = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_VersionText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VersionText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VersionText, 0);
    lv_obj_set_y(ui_VersionText, -100);
    lv_obj_set_align(ui_VersionText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VersionText, "Ver 1.0");
    lv_obj_set_style_text_color(ui_VersionText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VersionText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VersionText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessValue = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_BrightnessValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessValue, 30);
    lv_obj_set_y(ui_BrightnessValue, -60);
    lv_obj_set_align(ui_BrightnessValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessValue, "0");
    lv_obj_set_style_text_color(ui_BrightnessValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrightnessValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrightnessValue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 0);
    lv_obj_set_y(ui_Switch1, 35);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x89CFF0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Switch1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x0096FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Switch1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Switch1, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TempText = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_TempText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempText, 0);
    lv_obj_set_y(ui_TempText, 6);
    lv_obj_set_align(ui_TempText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempText, "Temperature");
    lv_obj_set_style_text_color(ui_TempText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -42);
    lv_obj_set_y(ui_Label2, 34);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "C");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 38);
    lv_obj_set_y(ui_Label3, 34);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "F");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BrightnessSlider, ui_event_BrightnessSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton, ui_event_BackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
	
	// Initialize the temperature switch state
    // You'll need to declare useFahrenheit as extern or find another way to track this
    // For now, let's assume it starts in Celsius (off position)
    //lv_obj_clear_state(ui_Switch1, LV_STATE_CHECKED);
	
	// if (useFahrenheit) {
    //    lv_obj_add_state(ui_Switch1, LV_STATE_CHECKED);
    //} else {
    //    lv_obj_clear_state(ui_Switch1, LV_STATE_CHECKED);
    //}

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Panel1 = NULL;
    ui_BrightnessSlider = NULL;
    ui_BrighnessText = NULL;
    ui_BackButton = NULL;
    ui_BackText = NULL;
    ui_VersionText = NULL;
    ui_BrightnessValue = NULL;
    ui_Switch1 = NULL;
    ui_TempText = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;

}
