// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Round_CO2

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel1;
extern void ui_event_BrightnessSlider(lv_event_t * e);
extern lv_obj_t * ui_BrightnessSlider;
extern lv_obj_t * ui_BrighnessText;
extern void ui_event_BackButton(lv_event_t * e);
extern lv_obj_t * ui_BackButton;
extern lv_obj_t * ui_BackText;
extern lv_obj_t * ui_VersionText;
extern lv_obj_t * ui_BrightnessValue;
extern void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_TempText;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

