// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Round_CO2

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_CO2Text;
extern lv_obj_t * ui_CO2Value;
extern lv_obj_t * ui_TemperatureText;
extern lv_obj_t * ui_TemperatureValue;

extern lv_obj_t * ui_TemperatureUnit;

extern lv_obj_t * ui_HumidityText;
extern lv_obj_t * ui_HumidityValue;
extern lv_obj_t * ui_HumidityPPMText;
extern lv_obj_t * ui_OnlineText;
extern void ui_event_NextButton(lv_event_t * e);
extern lv_obj_t * ui_NextButton;
extern lv_obj_t * ui_SettingsText;
extern lv_obj_t * ui_RedLed;
extern lv_obj_t * ui_Text400;
extern lv_obj_t * ui_Text2000;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

